### ISSUE TITLE
Event api

### ISSUE THREAD

**Issue by aguspina** [getsmarter/moodle-api#16]
Hey, with this gem can I interact with Moodle event 2 api?

**Comment by ryannealmes** [comment]
No. This gem is a wrapper used to easily interact with [web service functions](https://docs.moodle.org/dev/Web_service_API_functions). This is in a way an bunch of functions that open up access to data on Moodle.

From my understanding the [Events Api](https://docs.moodle.org/dev/Event_2#Events_API) is more for raising events within the Moodle framework to be used for pub/sub, logging, etc. The Events Api is usually referenced and consumed directly in code in Moodle e.g. when writing a plugin.
