### ISSUE TITLE
error handling

### ISSUE THREAD

**Issue by lizschley** [getsmarter/moodle-api#19]
I was having problems figuring out the problems I was having doing moodle web service calls, so I added a couple of lines to pull in all the error messaging, so I could get the debug message which provided me with the information I needed.  I forked the repository and added a couple of lines of code.  Please see the pull-request

I plan to fix the tests, so let me know if you are interested in merging this change.

**Comment by ryannealmes** [comment]
Could you maybe give examples of the error you were getting and how the additional information helped you resolve your issue? I would have expected the exception in the message key to be enough. There must be cases I don't know about and it may be useful to flesh it out a bit just so I can make sure we make it generic enough so we don't need to change this functionality again.

**Comment by ryannealmes** [comment]
Closing issue because a month has passed and the issue creator has gone silent.
