### ISSUE TITLE
How to get/use course overviewfiles/image in the another service

### ISSUE THREAD

**Issue by seyyah** [getsmarter/moodle-api#22]
Test code,

```ruby
require 'moodle-api'
Moodle::Api.configure do|c|
  c.host = 'https://moodle.example.com'
  c.token = 'TOKEN'
end

h = {
	field: "ids",
	value: "1"
}

response = Moodle::Api.core_course_get_courses_by_field(h)
```

Response,

```ruby
{"courses"=>
  [{"id"=>1,
    "overviewfiles"=>
     [{"filename"=>"test.png",
       "fileurl"=>"https://moodle.example.com/webservice/pluginfile.php/22/course/overviewfiles/test.png",
```

We want to use the `response["courses"][0]["overviewfiles"][0]["fileurl"]`. When we enter the `https://moodle.example.com/webservice/pluginfile.php/22/course/overviewfiles/test.png` in browser address bar, we get the token error

```html
 {"error":"A required parameter (token) was missing","stacktrace":null,"debuginfo":null,"reproductionlink":null}
```

When we try to the `https://moodle.example.com/webservice/pluginfile.php/22/course/overviewfiles/test.png?token=TOKEN`, we get the different error ~same error again~,

```html
{"error":"access control exception","errorcode":"accessexception","stacktrace":null,"debuginfo":null,"reproductionlink":null}
```

Anonymous user show the course overviewfiles/image in the browser. This url is different from webservice url,

- normal: https://moodle.example.com/pluginfile.php/22/course/overviewfiles/test.png
- webservice: https://moodle.example.com/webservice/pluginfile.php/22/course/overviewfiles/test.png

So, how to use the course overviewfiles/image in our custom app? I think you can solve with Token. But I don't know how to do it. On the other hand, would it be a security weakness to use the normal url vs werservice url?

**Comment by seyyah** [comment]
> When we try to the `https://moodle.example.com/webservice/pluginfile.php/22/course/overviewfiles/test.png?token=TOKEN`, we get the different error same error again,
> 
> ```
> {"error":"access control exception", "errorcode":"accessexception","stacktrace":null,"debuginfo":null,"reproductionlink":null}
> ```

In the admin/settings.php?section=debugging page, we change to debugging message to developer,

```html
{"error":"access control exception","errorcode":"accessexception","stacktrace":"* line 58 of \/webservice\/pluginfile.php: webservice_access_exception thrown\n","debuginfo":"Web service file downloading must be enabled in external service settings\nError code: accessexception","reproductionlink":"https:\/\/moodle.example.com\/"}
```

Then in the admin/webservice/service.php?id=2 page, we enable to downloading.

So we get image with the `https://moodle.example.com/webservice/pluginfile.php/22/course/overviewfiles/test.png?token=TOKEN` url.

But everyone show the our secret/token in the source code. I think it is security problem. How to get rid of this issue?

**Comment by seyyah** [comment]
> But everyone show the our secret/token in the source code. I think it is security problem. How to get rid of this issue?

In the admin/settings.php?section=webservicetokens page, we input our client IP in the IP restriction area of form. We can solve this way. But is there any advanced tech/practice/suggestion?

Best regards

**Comment by ryannealmes** [comment]
It seems like you are on the correct path. It makes sense to enable downloading from web services if it's a requirement you need. Regarding the token, you shouldn't include your token in your source code because it's definitely a security problem. 

To overcome this you should leverage something like [environment variables](https://www.honeybadger.io/blog/ruby-guide-environment-variables/). There are many ways to skin this cat, but this seems to be your best option.

Unless I am misunderstanding what you are trying to achieve.

**Comment by seyyah** [comment]
> It seems like you are on the correct path. It makes sense to enable downloading from web services if it's a requirement you need. Regarding the token, you shouldn't include your token in your source code because it's definitely a security problem.

I think so.

> To overcome this you should leverage something like [environment variables](https://www.honeybadger.io/blog/ruby-guide-environment-variables/). There are many ways to skin this cat, but this seems to be your best option.

I use the environment variables on the another Rails app for internal process. I have to use the token/environment variables at the html of Moodle Rails app as a open form. Even if I use the environment, token will be seen during the GET request, isn't it? How to get rid of this issue? I don't understant your suggestion. Can you clarify it?

**Comment by ryannealmes** [comment]
Hmm, yes I misunderstood what you were saying. I guess _if_ your app is behind moodle user authentication, you could leverage the users username and password to generate a token specific to them. That way if it's visible to them it doesn't really matter since it is limited for that user.

```ruby
Moodle::Api.configure({host: 'http://my_moodle_instance.com',
                       service: 'my_external_service', # ensure you include the shortname of the external service
                       username: 'jonsnow',
                       password: 'defendthewall'})

params = { 'criteria[0][key]' => 'firstname', 'criteria[0][value]' => 'Jon' }

Moodle::Api.core_user_get_users(params)
```
@rumanod do you have any suggestions here?

**Comment by rumanod** [comment]
Hi @ryannealmes. I agree that the best approach would be to generate a user specific token and using moodle authentication on the app.

**Comment by ryannealmes** [comment]
Closing this, but feel free to ask more questions @seyyah

**Comment by seyyah** [comment]
Thank you @ryannealmes & @rumanod
